---
- name: Set ssl configuration
  template: >
    src=ssl.conf.j2
    dest=/etc/nginx/conf.d/ssl.conf
  notify: Restart nginx

- template: >
    src=nginx.conf.j2
    dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: nginx
  notify: Restart nginx

- service: name=nginx state=started enabled=yes
