---
- name: "create user"
  user: name={{ user }} shell=/usr/bin/zsh groups='wheel' append=yes

- name: "ssh keys"
  authorized_key: key={{ authorized_keys }} user={{ user }} exclusive={{ authorized_keys_exclusive }}

- name: create directory for config
  file: path=/home/{{ user }}/git state=directory owner={{ user }} group={{ user }}

- name: clone configuration
  git: repo=https://github.com/qwazerty/config.git dest=/home/{{ user }}/git/config
  become: yes
  become_user: "{{ user }}"
  register: clone_configuration

- name: install configuration
  command: ./install.sh
  args:
    chdir: /home/{{ user }}/git/config
  become: yes
  become_user: "{{ user }}"
  when: clone_configuration.changed
