---
- lineinfile: dest=/etc/postfix/main.cf
    regexp="^{{ item.key }}"
    line="{{ item.key }} = {{ item.value }}"
  with_items:
  - { key: 'myhostname', value: '{{ postfix_myhostname }}' }
  - { key: 'inet_interfaces', value: '{{ postfix_inet_interfaces }}' }
  - { key: 'smtpd_milters', value: 'inet:127.0.0.1:8891' }
  - { key: 'non_smtpd_milters', value: '$smtpd_milters' }
  - { key: 'milter_default_action', value: 'accept' }
  notify: Restart postfix

- lineinfile: dest=/etc/aliases
  args:
    regexp: "^{% if item.key == 'wildcard' %}\\*{% else %}{{ item.key }}{% endif %}"
    line: "{% if item.key == 'wildcard' %}*{% else %}{{ item.key }}{% endif %}: {{ item.value }}"
  with_dict: postfix_aliases
  notify: Restart postfix

- command: opendkim-default-keygen
    creates=/etc/opendkim/keys/default.private

- lineinfile: dest=/etc/opendkim.conf
    regexp='^Domain'
    insertafter='^# Domain'
    line='Domain {{ postfix_myhostname }}'
  notify: Restart opendkim

- service: name={{ item }} state=started enabled=yes
  with_items:
  - postfix
  - opendkim
