---
- name: Install debian packages
  package: name={{ item }} state=present
  with_items:
  - transmission-daemon
  when: ansible_os_family == "Debian"

- name: Install redhat packages
  package: name={{ item }} state=present
  with_items:
  - transmission-daemon
  when: ansible_os_family == "RedHat"
