---
- name: named package
  include: package.yml
  tags:
  - package
  - named-package

- name: named configuration
  include: configuration.yml
  when: ansible_os_family == "RedHat"
  tags:
  - configuration
  - named-configuration
