---
- package: name={{ item }} state=present
  with_items:
  - mariadb
  - mariadb-server
  - MySQL-python

- package: name={{ item }} state=present
  with_items:
  - rabbitmq-server

- package: name={{ item }} state=present
  with_items:
  - openstack-keystone
  - httpd
  - mod_wsgi
  - python-openstackclient
  - memcached
  - python-memcached
