---
- lineinfile: dest=/etc/hosts
    regexp='\s{{ item.value.node_name }}\s'
    line="{{ item.value.private_ip }} {{ item.value.node_name }}"
    state=present
  with_dict: openstack_nodes

- template: dest=/root/.zsh/admin-openrc src=admin-openrc
