---
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts
    regexp='^{{ ansible_default_ipv4.address }}'
    line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    state=present
  when: ansible_default_ipv4.address is defined

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts
    regexp='^(?i){{ ansible_default_ipv6.address }}'
    line="{{ ansible_default_ipv6.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    state=present
  when: ansible_default_ipv6.address is defined
