---
- name: Install debian packages
  apt: name={{ item }} state=present
  with_items:
      - "{{ debian_packages }}"
  when: ansible_os_family == "Debian"

- name: Install redhat packages
  yum: name={{ item }} state=present
  with_items:
      - "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 21

- name: Install redhat packages
  dnf: name={{ item }} state=present
  with_items:
      - "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 22
