---
- name: Install debian packages
  apt: name={{ item }} state=present
  with_items:
      - "{{ debian_packages }}"
  when: ansible_os_family == "Debian"

- name: Install redhat packages
  yum: name={{ item }} state=present
  with_items:
      - "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat"
