---
- include: package.yml
  tags:
  - package
  - openvpn-package

- include: pki.yml
  when: inventory_hostname == "{{ openvpn_server }}"
  tags:
  - configuration
  - openvpn-configuration

- include: sync_pki.yml
  when: inventory_hostname != "{{ openvpn_server }}"
  tags:
  - configuration
  - openvpn-configuration

- include: configuration.yml
  tags:
  - configuration
  - openvpn-configuration
