---
#- name: Install debian packages
#  apt: name={{ item }} state=present
#  with_items:
#      - FIXME
#  when: ansible_os_family == "Debian"

- name: Install redhat packages
  dnf: name={{ item }} state=present
  with_items:
  - openvpn
  - easy-rsa
  when: ansible_os_family == "RedHat"
